#!/usr/bin/env node
const fs=require('fs');
const path=require('path');
const {spawnSync}=require('child_process');
const {readZip}=require('../rise-inspector/lib/zip-reader');

const VERSION='0.1.0';

function usage(){console.log(`\nStoryline Preview Pipeline v${VERSION}\n\nUsage:\n  npm run preview-storyline -- <storyline-web.zip> --output <folder> [--theme portfolio] [--open]\n\nThis runs extract → normalize → stateful web build and copies referenced published assets.\n`)}
function parse(argv){const a=argv.slice(2),oi=a.indexOf('--output'),ti=a.indexOf('--theme');return{input:a.find((x,i)=>!x.startsWith('--')&&!(oi>=0&&i===oi+1)&&!(ti>=0&&i===ti+1)),output:oi>=0?a[oi+1]:null,theme:ti>=0?a[ti+1]:'portfolio',open:a.includes('--open'),help:a.includes('--help')||a.includes('-h')}}
function run(script,args){const r=spawnSync(process.execPath,[script,...args],{stdio:'inherit'});if(r.status!==0)throw new Error(`${path.basename(script)} failed with exit code ${r.status}`)}
function isMeta(name){return name.startsWith('__MACOSX/')||name.split('/').some(p=>p.startsWith('._'))||name.endsWith('/.DS_Store')}
function archiveRoot(entries){const files=entries.filter(e=>!e.isDirectory&&!isMeta(e.fileName));if(!files.length)return'';const first=files[0].fileName.split('/')[0];return files.every(e=>e.fileName.split('/')[0]===first)?first:''}
function copyAssets(zipPath,normalizedDir,extractedDir){const assetsDoc=JSON.parse(fs.readFileSync(path.join(normalizedDir,'assets.json'),'utf8'));const archive=readZip(zipPath),root=archiveRoot(archive.entries);const map=new Map(archive.entries.filter(e=>!e.isDirectory&&!isMeta(e.fileName)).map(e=>[e.fileName,e]));let copied=0;for(const asset of assetsDoc.assets||[]){if(!asset.path)continue;const candidates=[root?`${root}/${asset.path}`:asset.path,asset.path];let entry=candidates.map(c=>map.get(c)).find(Boolean);if(!entry)entry=archive.entries.find(e=>!e.isDirectory&&!isMeta(e.fileName)&&e.fileName.endsWith(`/${asset.path}`));if(!entry)continue;const target=path.join(extractedDir,'assets',asset.path);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,archive.readEntry(entry));copied++}return copied}
function main(){const o=parse(process.argv);if(o.help||!o.input||!o.output){usage();process.exit(o.help?0:1)}const input=path.resolve(process.cwd(),o.input),output=path.resolve(process.cwd(),o.output);if(!fs.existsSync(input))throw new Error(`Storyline ZIP not found: ${input}`);fs.mkdirSync(output,{recursive:true});const extracted=path.join(output,'_extracted'),normalized=path.join(output,'_normalized');const root=path.resolve(__dirname,'..','..');console.log('\nSTORYLINE PREVIEW PIPELINE');console.log('==========================');console.log(`Source: ${input}`);console.log(`Output: ${output}`);run(path.join(root,'tools','storyline-extractor','index.js'),[input,'--output',extracted]);run(path.join(root,'tools','storyline-normalizer','index.js'),[extracted,'--output',normalized]);const copied=copyAssets(input,normalized,extracted);run(path.join(root,'builders','stateful-web','index.js'),[normalized,'--output',output,'--assets',path.join(extracted,'assets'),'--theme',o.theme]);console.log(`Published assets copied: ${copied}`);console.log(`Preview: ${path.join(output,'index.html')}`);if(o.open&&process.platform==='darwin')spawnSync('open',[path.join(output,'index.html')],{stdio:'ignore'});}
try{main()}catch(error){console.error(`\nError: ${error.message}\n`);process.exit(1)}
